### ISSUE TITLE
Name resolution failed: Could not contact DNS servers

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/unvanquished-infrastructure#10]
People reports DNS issues while using our services.

For example on September 23, 2020, Faalhaas [reported](https://www.gamingonlinux.com/2020/09/free-first-person-shooter-strategy-unvanquished-is-now-properly-open-source/comment_id=190279) on GamingOnLinux:

```09/23 22:41:22 [ERROR] CUID#7 - Download aborted. URI=https://cdn.unvanquished.net/unvanquished_0.51.1.torrent
Exception: [AbstractCommand.cc:351] errorCode=19 URI=https://cdn.unvanquished.net/unvanquished_0.51.1.torrent
  -> [AbstractCommand.cc:789] errorCode=19 CUID#7 - Name resolution for cdn.unvanquished.net failed:Could not contact DNS servers
```

On January 25, 2021, SteamLord reported on discord:

```
Exception: [AbstractCommand.cc:351] errorCode=19 URI=https://cdn.unvanquished.net/unvanquished_0.51.1.torrent
  -> [AbstractCommand.cc:789] errorCode=19 CUID#7 - Name resolution for cdn.unvanquished.net failed:Could not contact DNS servers
```

On January 09, 2021 I reported on IRC:

```
2021-01-09 02:06:47 +0100 <illwieckz>	I have seen people reporting dns issues for unvanquished.net
2021-01-09 02:06:55 +0100 <illwieckz>	I myself fail to load 1 page on 5
```

I noticed that very often, when browsing our website (blog, forums, wiki…), the page don't load, and when it fails it fails immediately the same ways it fails as soon as possible when a dns query reports there is a failure (not a timeout).

Any time I face that issue, I just click the « reload page » button on the web browser one or two time and then the page is back like if nothing have happened.

I experience this issue when browsing our websites whatever the ISP (both pro and consumers ISPs) or my location (tested from places distant up to 800 km).

**Comment by illwieckz** [comment]
This is typical issue I get with our websites, I never get such issue on any other website I visit:

[![dns resolution failure](https://dl.illwieckz.net/b/unvanquished/bugs/dns-resolution-failure/20210125-223802-000.unvanquished-web-dns-issue.png)](https://dl.illwieckz.net/b/unvanquished/bugs/dns-resolution-failure/20210125-223802-000.unvanquished-web-dns-issue.png)

As you see, the header and the background images are not loaded while everything else is.

The difference with everything else is that those two images are stored on the blog domain name, not the forum domain name, such issue typically happens when, in the same time window, one domain name responds and the other one does not.

Since both domains are hosted on the exact same infra-structure and the exact same infrastructure is used to connect to the server, one thing making the difference can be one domain being resolved and another one not being resolved.

Then some minutes later I got this while browsing the blog:

[![dns resolution failure](https://dl.illwieckz.net/b/unvanquished/bugs/dns-resolution-failure/20210125-225006-000.unvanquished-web-dns-issue.png)](https://dl.illwieckz.net/b/unvanquished/bugs/dns-resolution-failure/20210125-225006-000.unvanquished-web-dns-issue.png)

Note that's not specific to the blog. Sometime the forum does not load entirely, which is what we may expect if that's the forum domain that is failed to be resolved. Something the wiki does not load entirely.

When I edit the wiki, I usually get this issue at some point. I make a modification, I click preview, preview is displayed, I modify more, click preview again, *blam*, unable to connect, reload, click “yes” to resend form data, preview is displayed. I got it some hours ago while I was editing the wiki, but I get this pattern anytime I edit the wiki.

**Comment by illwieckz** [comment]
I just got a failure on unvanquished.net, I instantly reloaded and instantly got the web page.

In some ways, 4 days without reproducing the issue looks to me incredibly good in comparison with usual behaviour (I usually may get the issue multiple time a day). But this also means the problem is still there.

**Comment by necessarily-equal** [comment]
I think I've seen this yersterday, so it's still here. although rare

**Comment by illwieckz** [comment]
I get it on a daily basis.

**Comment by necessarily-equal** [comment]
```
Sys_StringToSockaddr: Error resolving master.unvanquished.net: Temporary failure in name resolution 
Failed to resolve hostname master.unvanquished.net 
Sys_StringToSockaddr: Error resolving master2.unvanquished.net: Temporary failure in name resolution 
Failed to resolve hostname master2.unvanquished.net 
```

**Comment by illwieckz** [comment]
I haven't seen this issues since years, this may have been fixed on DNS providers' side 2 or 3 years ago.
