### ISSUE TITLE
Mirroring repositories on GitLab?

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/unvanquished-infrastructure#11]
@Viech, @DolceTriade do you have anything against setting up repository mirrors on GitLab?

I have no time for this but @pretuer (Derek Owmui, `derek1` on IRC) proposes himself to do it.

At the time Microsoft bought GitHub I registered:

- https://gitlab.com/Unvanquished
- https://gitlab.com/UnvanquishedAssets
- https://gitlab.com/DaemonEngine

mainly to prevent name-squatting, but we never did anything with it, even not mirrors.

My own opinion on this is that I have nothing against mirrors (I would even not oppose a migration to GitLab — but not today as and we have others priority).

It looks like Derek setting up the mirrors for us would not really consumes our time (once we all answered the present thread and one of us have sent him some invitations).

What do you think about it?

Note that for `UnvanquishedAssets`, we may wand to do another scheme. As far as I know, GitLab allows to create groups of repositories in an organization, so maybe we can have `https://gitlab.com/Unvanquished/UnvanquishedAssets/map-chasm_src.dpkdir`. But before we think about the scheme for assets, Derek can already mirror `Unvanquished` and `DaemonEngine` repositories.

**Comment by Viech** [comment]
I see no reasons either for or against such a mirror. A mirror in the opposite direction would make sense such that we could remain visible on the larger platform. This direction does …?

**Comment by illwieckz** [comment]
There is no urge and there are other priorities (like releasing Unvanquished `0.55.0` to begin with…), but the topic came again into discussion these days.

This thread has the purpose of gathering intel and knowledge about the feasibility of migrating the repositories to somewhere else than GitHub, so let's do.

We migrated from SourceForge to GitHub around the year 2012 while SourceForge was in bad shape. GitHub served well but is subject to some limitations and problems that may be avoided when being hosted elsewhere.

Self-hosting is ruled out as we don't have the manpower for that.

Among candidates may be platforms like CodeBerg or GitLab.com. GitLab has always been the first candidate we thought about for historical purposes, but we are open to other suggestions.

- GitLab.com is the platform used by our friends of Xonotic, we have very similar needs and it looks to work for them (game engine, game code, game data, various authoring tools…), it is also used by other flagship projects like [Samba](https://gitlab.com/samba-team/samba/) and others.
- GitLab.com was basically the platform where many people migrated to when Microsoft bought GitHub when “[Microsoft [needed] the love of developers](https://www.businessinsider.com/why-microsoft-should-buy-github-2018-6)“. This also mean GitLab is well proven for importing projects from GitHub with dedicated tools on that purpose, that are or at least were massively used.
- GitLab (the software itself) is used (as self-hosted) by many key and very-large open source projects like [Freedesktop.org](https://gitlab.freedesktop.org/), [KDE](https://invent.kde.org), [GNOME](https://gitlab.gnome.org/), [Wine](https://gitlab.winehq.org), [Debian](https://salsa.debian.org), [ArchLinux](https://gitlab.archlinux.org)…
- Some Unvanquished-related software is already on GitLab like [Mantis](https://gitlab.com/Viech/Mantis/).
- We already have an Unvanquished organization on GitLab and th [Unvanquished data dump](https://gitlab.com/Unvanquished/UnvanquishedData/unvanquished-data-dump) repository is already on GitLab and always had been, because historically GitLab has been more permissive than GitHub on storage size.
- The [temporary repository](https://gitlab.com/Unvanquished/UnvanquishedData/unvanquished-data-cleaning-room) that was done to produce our data repositories was on GitLab too.

So the software is expected to be well tailored for FLOSS development and big projects.

GitHub has some problems that may not exist on GitLab.

- Historically GitLab allowed larger repositories than GitHub, it now requires to ask for it but it can still be free for us.
- GitLab now provides sub-organizations, so `Unvanquished`, `UnvanquishedAssets` and `DaemonEngine` can be all a childs of `Unvanquished`. It would allow us to move issues from `DaemonEngine` to `Unvanquished` for example, which is not possible on GitHub.
- GitLab provides a parent issue view and a parent merge request view, making possible to get a list of all issues or merge requests in all repository. This is not available on GitHub (some said this may be a paid option).
- GitLab makes possible to categorize labels (the label prefix is actually a label class), GitHub doesn't.
- GitLab makes possible to have sub-threads in issues and merge requests, being able to collapse the whole thread when needed. In GitHub it is only available in pull requests and only for code review (the thread needs to be attached to a specific line).

In a more general way, GitLab is now the leading platform in term of available features and developer-oriented workflow, GitHub is now lagging behind GitLab for years. This is probably true since 5 years or more.

**Comment by illwieckz** [comment]
The opportunity to quit GitHub went in the discussion these days while talking about the fact GitHub is now hiding parts of public projects to non-logged in users, requiring users to register and login to read what is meant to be public. It means the public projects are in fact made semi-private at the will of GitHub, and that GitHub is actually opaque web:

Here is an example of how two comments are hidden by GitHub in a thread of publicly-readable comments:

[![github opaque web](https://dl.illwieckz.net/b/github/shots/opaque-web/20240918-220521-001.github-opaque-web.png)](https://dl.illwieckz.net/b/github/shots/opaque-web/20240918-220521-001.github-opaque-web.png)

But those comments contains nothing private:

[![github opaque web](https://dl.illwieckz.net/b/github/shots/opaque-web/20240918-221110-000.github-opaque-web.png)](https://dl.illwieckz.net/b/github/shots/opaque-web/20240918-221110-000.github-opaque-web.png)

**Comment by illwieckz** [comment]
Well, actually this thread was more about mirroring than migrating. It would be better to have a dedicated thread for migrating. I'll create one for migrating, moves my comments there, and likely close this one as it looks like we're not really having much interest in mirroring and the one having proposed help left a very long time ago.
