### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/unvanquished-infrastructure#18]
I have updated few unvanquished PRs today, and all builds fail, something about python I think.

**Comment by illwieckz** [comment]
Was a mistake on mine on a script used by our CI. I enable the bash feature to fail on usage of unset variables and had not catch all the occurrences… 😁️

Anyway CI build of https://github.com/Unvanquished/Unvanquished/pull/1735 is now fixed

Failed build of https://github.com/Unvanquished/Unvanquished/pull/1738 are likely to be mistakes in code.
