### ISSUE TITLE
Wiki CSS: some box have white background

### ISSUE THREAD

**Issue by necessarily-equal** [Unvanquished/unvanquished-infrastructure#22]
Having a white block in some places in the middle of a dark theme can be quite jarring. It would be good to avoid that.

Example: https://wiki.unvanquished.net/wiki/Install_and_play or https://wiki.unvanquished.net/wiki/Entities/env_speaker

**Comment by illwieckz** [comment]
Some are editable without advanced permission. For example when editing the `Install and play` page:
https://wiki.unvanquished.net/index.php?title=Install_and_play&action=edit
One can notice the list of `Templates used on this page`, and edit the `Note` template:
https://wiki.unvanquished.net/index.php?title=Template:Note&action=edit

I did it, though it may be better.

I also edited `EntityDocumentationNotice` to rely on `Note` so it inherits the colors:
https://wiki.unvanquished.net/wiki/Template:EntityDocumentationNotice

Note that pages relying on a template needs to be regenerated: just click edit and save, it will not commit anything but force the regeneration of the page from templates. We may do a crontask to force the regeneration from time to time.
