### ISSUE TITLE
Some web pages are out of date

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/unvanquished-infrastructure#29]
Paste from https://wiki.unvanquished.net/wiki/User:SeanCJ/Webpage-parts_Out-of-date by @SeanScherer

> Corrections / Improvements:
> ================================
> 
> https://unvanquished.net/join-us/
> 
> --> change to reflect that beta has been released :D ! 
> ( and a couple other minor things)
> 
> ----------------
> 
> 
> Beta is out :)
> -----------------
> 
> * "Pre-alpha began September 2011, and our first alpha release was March 2012. We have made dozens and dozens alpha releases since then, and we expect to reach beta soon."
> --> Beta released 2021
> 
> * Contact	"We are always looking to expand our team, and currently we would like to fill several positions to help bring us closer to beta next year."
> --> :P
> 
> 
> Other small stuff
> ----------------------
> 
> * Article List:
> -->Update a little: Add "10 years of Unvanquished", and probably "Beta Release Blogpost".
> 
> * "The team behind Unvanquished is an international one, and developers range from experienced hobbyists to professionals contributing their free time, all of whom are centrally coordinated on our IRC channel and forums."
> --> Link to IRC channel (and possibly Forum).
> 
> * "Our engine was famous in the Open Source community for its modern features but time is passing and we have to keep up with what people expects from games today."
> -->"... expect ..." 
> (I'd also change to "we *want* to keep up with what people expect .." - but thats just style/preference)

**Comment by illwieckz** [comment]
Now fixed.

**Comment by SeanScherer** [comment]
Oh, nice, thank you :) !
